version: '3.7'

services:
  db:
    container_name: scheduler-db
    image: postgres:latest
    restart: always
    env_file:
      - db.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASS}'
      POSTGRES_DB: '${POSTGRES_DB_NAME}'
    volumes:
      - ./vol:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql